# Generated by Django 5.2.4 on 2025-08-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrequest',
            name='teacher_response',
            field=models.TextField(blank=True, verbose_name='Ответ учителя'),
        ),
    ]
