# Generated by Django 5.2.4 on 2025-08-17 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принят'), ('rejected', 'Отклонен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус запроса')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение от ученика')),
                ('teacher_response', models.TextField(blank=True, verbose_name='Ответ учителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_requests', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Запрос на обучение',
                'verbose_name_plural': 'Запросы на обучение',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='StudentTeacherRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала обучения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки учителя')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_teacher_relationships', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Связь ученик-учитель',
                'verbose_name_plural': 'Связи ученик-учитель',
                'ordering': ['-started_at'],
                'unique_together': {('student', 'teacher')},
            },
        ),
    ]
