# Generated by Django 5.2.4 on 2025-08-20 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_category'),
        ('students', '0002_studentrequest_student_response_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySharingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус запроса')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение от учителя')),
                ('student_response', models.TextField(blank=True, verbose_name='Ответ ученика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.category', verbose_name='Категория')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sharing_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sharing_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Запрос на передачу категории',
                'verbose_name_plural': 'Запросы на передачу категорий',
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'student', 'category')},
            },
        ),
    ]
