# Generated by Django 5.2.4 on 2025-08-10 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(help_text='Введите английское слово', max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Английское слово')),
                ('russian_translation', models.CharField(help_text='Введите перевод на русский язык', max_length=200, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Русский перевод')),
                ('transcription', models.CharField(blank=True, help_text='Фонетическая транскрипция (например, [ˈwɜːrd])', max_length=150, null=True, verbose_name='Транскрипция')),
                ('definition', models.TextField(blank=True, help_text='Определение слова на английском языке', max_length=500, null=True, verbose_name='Определение на английском')),
                ('example_sentence', models.TextField(blank=True, help_text='Пример использования слова в предложении', max_length=300, null=True, verbose_name='Пример предложения')),
                ('category', models.CharField(choices=[('general', 'Общие'), ('business', 'Бизнес'), ('academic', 'Академические'), ('travel', 'Путешествия'), ('food', 'Еда'), ('technology', 'Технологии'), ('medicine', 'Медицина'), ('sports', 'Спорт'), ('art', 'Искусство'), ('science', 'Наука'), ('nature', 'Природа'), ('family', 'Семья'), ('emotions', 'Эмоции'), ('clothes', 'Одежда'), ('house', 'Дом'), ('other', 'Другое')], default='general', max_length=20, verbose_name='Категория')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Начинающий'), ('elementary', 'Элементарный'), ('intermediate', 'Средний'), ('upper_intermediate', 'Выше среднего'), ('advanced', 'Продвинутый'), ('proficiency', 'Профессиональный')], default='beginner', max_length=20, verbose_name='Уровень сложности')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Выучено')),
                ('times_practiced', models.PositiveIntegerField(default=0, verbose_name='Количество повторений')),
                ('last_practiced', models.DateTimeField(blank=True, null=True, verbose_name='Последнее изучение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('words_count', models.PositiveIntegerField(default=0, verbose_name='Количество слов')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Правильных ответов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('words_studied', models.ManyToManyField(blank=True, to='dictionary.word', verbose_name='Изученные слова')),
            ],
            options={
                'verbose_name': 'Сессия изучения',
                'verbose_name_plural': 'Сессии изучения',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WordStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_words_added', models.PositiveIntegerField(default=0, verbose_name='Всего добавлено слов')),
                ('words_learned', models.PositiveIntegerField(default=0, verbose_name='Выучено слов')),
                ('total_practice_time', models.PositiveIntegerField(default=0, verbose_name='Общее время изучения (минут)')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущая серия дней')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='Лучшая серия дней')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='Последняя дата изучения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='word_statistics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика слов',
                'verbose_name_plural': 'Статистика слов',
            },
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['user', 'is_learned'], name='dictionary__user_id_502b44_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['user', 'category'], name='dictionary__user_id_6119d4_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['user', 'difficulty_level'], name='dictionary__user_id_36e2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['last_practiced'], name='dictionary__last_pr_7c195c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('user', 'english_word')},
        ),
    ]
