# Generated by Django 5.2.4 on 2025-08-16 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_word_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(help_text='Категория слова', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True, help_text='Определение на английском', max_length=500, null=True, verbose_name='Определение'),
        ),
        migrations.AlterField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True, help_text='Пример предложения', max_length=300, null=True, verbose_name='Пример'),
        ),
        migrations.AlterField(
            model_name='word',
            name='last_practiced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее повторение'),
        ),
        migrations.AlterField(
            model_name='wordstatistics',
            name='best_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальная серия дней'),
        ),
        migrations.AlterField(
            model_name='wordstatistics',
            name='last_study_date',
            field=models.DateField(blank=True, null=True, verbose_name='Последняя дата обучения'),
        ),
        migrations.AlterField(
            model_name='wordstatistics',
            name='total_practice_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее время практики (мин)'),
        ),
        migrations.AlterField(
            model_name='wordstatistics',
            name='total_words_added',
            field=models.PositiveIntegerField(default=0, verbose_name='Добавлено слов'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('user', 'english_word', 'category')},
        ),
    ]
