# Generated by Django 5.2.4 on 2025-08-20 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_category_options_category_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='word',
            new_name='dictionary__user_id_26c19d_idx',
            old_name='dictionary__user_id_6119d4_idx',
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(help_text='Категория слова', on_delete=django.db.models.deletion.CASCADE, related_name='words', to='dictionary.category', verbose_name='Категория'),
        ),
    ]
