# Generated by Django 5.2.4 on 2025-08-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_rename_dictionary__user_id_6119d4_idx_dictionary__user_id_26c19d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-21 01:23:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
