# Generated by Django 5.2.4 on 2025-08-16 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0002_alter_word_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(default=list, verbose_name='Категории для тестирования')),
                ('total_words', models.PositiveIntegerField(default=0, verbose_name='Общее количество слов в тесте')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Правильные ответы')),
                ('incorrect_answers', models.PositiveIntegerField(default=0, verbose_name='Неправильные ответы')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Тест завершен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия тестирования',
                'verbose_name_plural': 'Сессии тестирования',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=200, verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(verbose_name='Правильный ответ')),
                ('answer_time', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word', verbose_name='Слово')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testsession', verbose_name='Сессия теста')),
            ],
            options={
                'verbose_name': 'Ответ в тесте',
                'verbose_name_plural': 'Ответы в тестах',
            },
        ),
    ]
