# Generated by Django 5.2.4 on 2025-08-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность выполнения'),
        ),
    ]
