# Generated by Django 5.2.4 on 2025-08-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testsession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность выполнения (сек)'),
        ),
    ]
