# Generated by Django 5.2.3 on 2025-08-03 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, help_text='Информация о браузере', verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='Успешный вход')),
                ('failure_reason', models.CharField(blank=True, max_length=100, verbose_name='Причина неудачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История входа',
                'verbose_name_plural': 'История входов',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Формат: +7 (XXX) XXX-XX-XX', max_length=20, null=True, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(blank=True, help_text='Загрузите фото профиля', null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, help_text='Расскажите немного о себе', max_length=500, verbose_name='О себе')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('registration_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP регистрации')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Последний IP входа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_level', models.CharField(choices=[('beginner', 'Начинающий'), ('elementary', 'Элементарный'), ('intermediate', 'Средний'), ('upper_intermediate', 'Выше среднего'), ('advanced', 'Продвинутый'), ('proficiency', 'Профессиональный')], default='beginner', max_length=20, verbose_name='Уровень английского')),
                ('daily_goal', models.PositiveIntegerField(default=10, verbose_name='Ежедневная цель (минут)')),
                ('notification_time', models.TimeField(blank=True, null=True, verbose_name='Время напоминаний')),
                ('total_study_time', models.PositiveIntegerField(default=0, verbose_name='Общее время изучения (минут)')),
                ('words_learned', models.PositiveIntegerField(default=0, verbose_name='Изучено слов')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Пройдено тестов')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущая серия дней')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='Лучшая серия дней')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
