# Generated by Django 5.2.4 on 2025-08-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель')], default='student', max_length=10, verbose_name='Роль пользователя'),
        ),
    ]
