# Generated by Django 5.2.4 on 2025-08-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=6, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('purpose', models.CharField(choices=[('register', 'Регистрация'), ('login', 'Вход')], max_length=10, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
                'indexes': [models.Index(fields=['email', 'code'], name='authen_veri_email_d31361_idx')],
            },
        ),
    ]
